apiVersion: v1
kind: Service
metadata:
  name: {{ include "rbac-apiserver.fullname" . }}
  labels:
    {{- include "rbac-apiserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: https
    protocol: TCP
    name: https
  - port: 50051
    protocol: TCP
    name: grpc
  selector:
    {{- include "rbac-apiserver.selectorLabels" . | nindent 4 }}
