apiVersion: authorization.open-cluster-management.io/v1alpha1
kind: PermissionRequest
metadata:
  name: check-group-deployment-update
spec:
  group: apps
  resource: deployments
  verb: update
  cluster: cluster1
  namespace: development
  name: my-app
