apiVersion: authorization.open-cluster-management.io/v1alpha1
kind: PermissionRequest
metadata:
  name: check-bob-cluster1-production
spec:
  group: apps
  resource: deployments
  verb: create
  cluster: cluster1
  namespace: production
  name: web-app
